### ISSUE TITLE
travis.yml

### ISSUE THREAD

**Issue by liudahu** [FE-star/2018.1#6]
```
before_install:
- npm install -g karma
  - npm install
 dist: trusty
 addons:
   chrome: stable
sudo: required
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 8.9.4

#运行的脚本命令
script:
  - npm run test

before_script:
#  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
```

这是我配置文件,但是不知道错再哪里
